channel_size = 16
dram_config = 'HBM'
icnt = 'Mesh'
ideal_icnt = false
ideal_l3cache = false
ideal_memory = false
init_running_mode = 'RealRoundGap'
l1_hit_latency = 1
l3_cache_size = 1
l3_cache_type = 'Simple'
l3_hit_latency = 15
level_sync = false
mems = 8
miss_latency = 120
multi_port = 1
n_clauses = 1
n_watchers = 16
num_writer_entry = 1
num_writer_merge = 1
pipeline_clause_value_read = true
private_cache_size = 1
ramu_cache_config = 'HBM'
seq = false
single_watcher = false
value_miss_hit_l3 = true
watcher_to_clause_icnt = 'Mesh'
watcher_to_clause_type = 'Icnt'
watcher_to_writer_icnt = 'Mesh'

[private_cache_config]
alway_hit = false
associativity = 4
block_size = 64
channels = 1
sets = 4

[l3_cache_config]
alway_hit = false
associativity = 4
block_size = 64
channels = 8
sets = 65536
